import { FormEvent, useState } from 'react';
import { GuardLine, GuardOutcome, talkToCastleGuard } from '../lib/castleGuardAi';

export function CastleGuardDialogue({ onClose, onOutcome }: { onClose: () => void; onOutcome: (outcome: Exclude<GuardOutcome, 'continue'>) => void }) {
  const [lines, setLines] = useState<GuardLine[]>([{ speaker: 'guard', text: 'Стой, чужак. Мы охраняем эти ворота. Зачем тебе понадобилось в замок?' }]);
  const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); const message=text.trim().slice(0,240); if(!message||loading)return; const next=[...lines,{speaker:'player' as const,text:message}];setLines(next);setText('');setLoading(true);setError('');try{const result=await talkToCastleGuard(lines,message);setLines([...next,{speaker:'guard',text:result.reply}]);if(result.outcome==='fight'||result.outcome==='peace'||result.outcome==='farewell'){const finalOutcome: 'fight'|'peace'|'farewell'=result.outcome;window.setTimeout(()=>onOutcome(finalOutcome),900);}}catch{setError('Страж не расслышал тебя. Попробуй ещё раз.');}finally{setLoading(false);}};
  return <div className="guard-ai-dialogue"><div className="guard-ai-heading"><div><small>ИИ-ДИАЛОГ</small><strong>ДВА РЫЦАРЯ-СТРАЖА</strong></div><button onClick={onClose}>✕</button></div><div className="guard-ai-lines">{lines.map((line,index)=><p key={index} className={line.speaker}><b>{line.speaker==='guard'?'РЫЦАРИ':'ТЫ'}</b>{line.text}</p>)}</div>{error&&<div className="guard-ai-error">{error}</div>}<form onSubmit={submit}><input autoFocus value={text} maxLength={240} onChange={(event)=>setText(event.target.value)} placeholder="Напиши рыцарям что угодно…" disabled={loading}/><button disabled={loading||!text.trim()}>{loading?'ДУМАЮТ…':'СКАЗАТЬ'}</button></form></div>;
}
